### PR TITLE
Try using azure for linux_ppc64le

### PR DESCRIPTION
**Pull request by chrisburr**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by ax3l** [comment]
But really, really @conda-forge-admin please rerender

**Comment by ax3l** [comment]
@conda-forge/core do we have further CI templates that support ppc64le builds? Something seams wrong here:
Travis:
https://travis-ci.org/conda-forge/adios-feedstock/builds/606953287
https://travis-ci.org/conda-forge/adios-python-feedstock/builds/607053128

Azure: does not rerender

**Comment by ax3l** [comment]
should we bump the build number?

**Comment by chrisburr** [comment]
I don't think so, it's the same build and just moving CI provider to avoid whatever the network issue is.

**Comment by ax3l** [comment]
Only downside: emulated azure builds take 1hr while native builds finish in 15min ;)

**Comment by isuruf** [comment]
@ax3l, you can download the source from github and run autoconf on it.

**Comment by ax3l** [comment]
I do not fully follow. I can download and build, for many months, but now travis stopped downloading it with some network issue.

**Comment by chrisburr** [comment]
Feel free to close this and use @isuruf's suggestion if you prefer (that probably justifies a build number bumpy).

**Review by ax3l — APPROVED** [review]
Thanks a lot for the help, great we can migrate over :)

**Pull request merged**
